sudo: required
services:
- docker
language: java
jdk: oraclejdk8
branches:
  only:
  - master
before_install:
- docker version
- docker info
- node --version
- npm --version
script:
- cd alma-server/src/main/resources
- pwd
- npm install -g gulp
- npm install
- gulp minify
- cd ../../../../
- mvn clean verify -f alma-server/pom.xml -e
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker images
- docker push hodororganizo/alma-server:latest
deploy:
  provider: releases
  api_key:
    secure: cot6I/lv7ZE6KL8hMCcyr54P+1JozZB18KRQCSTk6Py34wAE03RFWW0eGEOVuzjfdgWBwANCI5+GGireNh0n2qfYhz92TFPzraPM7dVns71BctbhT8C66Za/RrIXrrrkwlCNHu4JnmBu0yfMThunW/MyB4r9HIT2VvVLMvjbSstJPkvNFgvxOyDk8u/iQefjOc4JRga0MuIg21I+Ajo0JIG5phF0+c6whQero6l8O5u9ygX7w+CK+D8nRilijTtD9znfHCSZG62dWNYWcpzHtACgJ+dIBH23m9A5uzQNurriI58d5wQvW6vSmcyPICgZXRISlxXTOjgcpwSslOlIKQsQDfeaWDHQDIRq9yeE+SqnomD1b1m7lDXgbe319eYvbCiVSejiPhGx5uMjK4d1Wo4iX22ndifeK6g6JiE7Cnbe1/NOSkBSOxF3UnnbANkRGxMaW4l84ktk4rwXBRnSQ2j/nC3suLrPOnE+vLqterhyNophkl/GOECzksVqj33anWQgwQyuxaEAS5wc1WRfWxjws/vqvKgbC+Z5jxbMr2lty1Ae3+gOnNkwmdjbX3948mH8H6HxsU61uc3CHR6iQHNseEoWr9ss1ONff2GTatt0c0Q1UvPg42HU/t0TLVbxFda958a7hCO9UE5jiTEWYriu5kaQ4RzmpC1y7kgT/qs=
  file: alma-server/target/alma-server-1.0.0-SNAPSHOT.jar
  on:
    repo: hodororganizo/alma-m2-2017
    tags: yes
